LICENSE.txt

LICENSE Copyright Fix

---

build.gradle
samples/http-sample/build.gradle
samples/sample/build.gradle
ziti/build.gradle

switch from kotlin build files to groovy

Gradle groovy

---

.github/workflows/publish-release.yml

Signed-off-by: Eugene K <eugene.kobyakov@netfoundry.io>

rename release workflow

---

ziti-android/src/main/java/org/openziti/android/AndroidSystemInfoProvider.kt
ziti-android/src/main/resources/META-INF/services/org.openziti.util.SystemInfoProvider
ziti/src/main/kotlin/org/openziti/api/Controller.kt
ziti/src/main/kotlin/org/openziti/api/types.kt
ziti/src/main/kotlin/org/openziti/util/SystemInfo.kt

fixes Android clients showing up as Linux in MOP

supply correct envInfo on Android

---

.github/workflows/publish-release.yml
build.gradle
publish.gradle
ziti-android/build.gradle
ziti-netty/build.gradle
ziti/build.gradle

transition publishing from jcenter to maven central repo

Ossrh publishing

---

ziti/src/main/kotlin/org/openziti/api/types.kt

add InterceptConfig.toString()

---

samples/ziti-enroller/src/main/kotlin/org/openziti/ZitiEnroller.kt
ziti/src/main/kotlin/org/openziti/Exceptions.kt
ziti/src/main/kotlin/org/openziti/Ziti.kt
ziti/src/main/kotlin/org/openziti/ZitiContext.kt
ziti/src/main/kotlin/org/openziti/api/Controller.kt
ziti/src/main/kotlin/org/openziti/api/mfa.kt
ziti/src/main/kotlin/org/openziti/api/types.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiContextImpl.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiImpl.kt
ziti/src/main/kotlin/org/openziti/posture/DefaultPostureService.kt

implemented:
- enrollment/verification into MFA
- MFA authentication
- reset via recovery code

MFA support

---

samples/ziti-enroller/src/main/kotlin/org/openziti/ZitiEnroller.kt
ziti-android/src/main/java/org/openziti/android/Ziti.kt
ziti/src/main/kotlin/org/openziti/ZitiContext.kt
ziti/src/main/kotlin/org/openziti/api/types.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiContextImpl.kt

add Service.failingPostureChecks

add MFA status to ZitiContext

---

samples/sample-host/src/main/kotlin/org/openziti/sample/netcat/NetcatHost.kt
samples/ziti-enroller/build.gradle
samples/ziti-enroller/src/main/kotlin/org/openziti/ZitiEnroller.kt
ziti-android/build.gradle
ziti-android/src/main/java/org/openziti/android/Ziti.kt
ziti-android/src/main/java/org/openziti/android/ZitiContextViewModel.kt
ziti-android/src/main/java/org/openziti/android/ZitiViewModel.kt
ziti/build.gradle
ziti/src/main/kotlin/org/openziti/Ziti.kt
ziti/src/main/kotlin/org/openziti/ZitiContext.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiContextImpl.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiImpl.kt

Implements ZitiViewModel and ZitiContextViewModel for easier Ziti integration in the apps

Ziti view model

---

samples/ziti-half-close/src/main/kotlin/HalfCloseTest.kt
ziti/src/main/kotlin/org/openziti/api/Controller.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiContextImpl.kt
ziti/src/main/kotlin/org/openziti/net/nio/AsyncSocketImpl.kt

- clear controller client connections
- close channels

fix shutdown

---

ziti/src/main/kotlin/org/openziti/net/nio/AsyncSocketImpl.kt
ziti/src/main/kotlin/org/openziti/net/nio/SyncSocketChannel.kt
ziti/src/main/kotlin/org/openziti/net/nio/ZitiSelectorProvider.kt

Adding just the features required by Oracle JDBC drivers up to OJDBC11

Adding nio SocketChannel implementation required for Oracle driver

---

ziti/build.gradle

Adding fatJar to simplify integrating Ziti into java-based tooling such as IDEs and SQL editors

Add fatJar artifact

---

ziti-android/src/main/java/org/openziti/android/InfoProviders.kt
ziti-android/src/main/java/org/openziti/android/Ziti.kt
ziti-android/src/main/resources/META-INF/services/org.openziti.util.DebugInfoProvider
ziti/src/main/kotlin/org/openziti/util/DebugInfoProvider.kt
ziti/src/main/kotlin/org/openziti/util/Info.kt
ziti/src/main/resources/META-INF/services/org.openziti.util.DebugInfoProvider

allow app to provide additional info for feedback

refactor feedback/debug info collection

---

build.gradle
ziti-android/build.gradle
ziti-android/src/main/java/org/openziti/android/ZitiContextViewModel.kt

use Android SDK 31 (android-12)

---

build.gradle
ziti/build.gradle
ziti/src/main/kotlin/org/openziti/api/Controller.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiImpl.kt
ziti/src/main/kotlin/org/openziti/net/Transport.kt
ziti/src/main/kotlin/org/openziti/net/internal/BypassProvider.kt
ziti/src/main/kotlin/org/openziti/net/internal/SSLEngineWrapper.kt
ziti/src/main/kotlin/org/openziti/net/internal/SocketChannelSocket.kt
ziti/src/main/kotlin/org/openziti/net/internal/Sockets.kt
ziti/src/main/kotlin/org/openziti/net/nio/AsyncSocketImpl.kt
ziti/src/main/kotlin/org/openziti/net/nio/NetUtils.kt
ziti/src/test/kotlin/org/openziti/net/TransportTest.kt

add tls-channel dependecy to use for ER connections
improve bypass socket setup (only used for controller connections)

Use tls-channel lib

---

samples/ziti-spring-boot/HELP.md
samples/ziti-spring-boot/build.gradle
samples/ziti-spring-boot/src/main/kotlin/org/openziti/sample/springboot/Main.kt
samples/ziti-spring-boot/src/main/kotlin/org/openziti/sample/springboot/ZitiSpringBootApplication.kt
samples/ziti-spring-boot/src/main/resources/application.properties
ziti-springboot/README.md
ziti-springboot/build.gradle
ziti-springboot/src/main/kotlin/org/openziti/springboot/ZitiEndpoint.kt
ziti-springboot/src/main/kotlin/org/openziti/springboot/ZitiProperties.kt
ziti-springboot/src/main/kotlin/org/openziti/springboot/ZitiProtocol.kt
ziti-springboot/src/main/kotlin/org/openziti/springboot/ZitiProtocolCustomizer.kt
ziti-springboot/src/main/kotlin/org/openziti/springboot/ZitiTomcatCustomizer.kt

add spring boot zitification sample

initial spring boot zitification

---

ziti/src/main/kotlin/org/openziti/impl/ChannelImpl.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiContextImpl.kt
ziti/src/main/kotlin/org/openziti/net/Channel.kt
ziti/src/main/kotlin/org/openziti/net/ZitiSocketChannel.kt

normalize connection log messages 
include connections in the debug dump
fix: blocking ziti dial if some channels are not connected

improve connection level logging

---

gradle.properties
ziti-netty/src/main/kotlin/org/openziti/netty/ZitiChannel.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiContextImpl.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiImpl.kt
ziti/src/main/kotlin/org/openziti/net/ZitiServerSocketChannel.kt

make Ziti netty channel conform to expectations

Ziti netty fixes

---

ziti-netty/src/main/kotlin/org/openziti/netty/ZitiChannel.kt
ziti/src/main/kotlin/org/openziti/net/ZitiServerSocketChannel.kt

rebind hosting/server connection after dropped connection to ER

---

README.rst

adds a new banner to the top of the readme

add new banner to readme

---

ziti/src/main/kotlin/org/openziti/net/nio/AsyncSocketImpl.kt

avoid cast exception on ziti wrapped socket

---

samples/ziti-spring-boot/build.gradle
ziti/src/main/kotlin/org/openziti/api/types.kt
ziti/src/main/kotlin/org/openziti/impl/ChannelImpl.kt
ziti/src/main/kotlin/org/openziti/net/Message.kt
ziti/src/main/kotlin/org/openziti/net/ZitiProtocol.kt
ziti/src/main/kotlin/org/openziti/net/ZitiServerSocketChannel.kt

Support connection inspection

---

.github/dependabot.yml
.github/workflows/gradle-build.yml
.github/workflows/publish-release.yml
gradle/libs.versions.toml
ziti-springboot-client/build.gradle
ziti-springboot/build.gradle

Consolidate springboot version

---

.github/workflows/publish-release.yml
build.gradle
edge-api/build.gradle
gradle/libs.versions.toml

edge-api module publishing

---

samples/sample-okhttp/build.gradle
ziti/src/main/kotlin/org/openziti/api/intercept.kt
ziti/src/main/kotlin/org/openziti/impl/ZitiContextImpl.kt

populate ZitiAddress.Dial.identity field if requested by intercept.v1 config
[fixes #620]

populate ZitiAddress.Dial.identity field

---

.github/workflows/gradle-build.yml
.github/workflows/publish-release.yml

some dependencies are now built with JVM 21

switch to JVM 21
